### ISSUE TITLE
yooo gboy

### ISSUE THREAD

**Issue by enyoghasim** [Chidalu567/reactify#1]
hw u doin

**Comment by ration665** [comment]
how far, no dey give me issue in codeing

**Comment by ration665** [comment]
how far na code

**Comment by ration665** [comment]
guy, i am having issue in installing mongodb on my system. I used robo3t and it is not working at all.

**Comment by enyoghasim** [comment]
go to their documentation

**Comment by Chidalu567** [comment]
Serious bro, the docs is what I follow

**Comment by enyoghasim** [comment]
are u srz?

**Comment by ration665** [comment]
guy always do promo with your website bro

**Comment by enyoghasim** [comment]
Ure high abi?

**Comment by Chidalu567** [comment]
This issue is a pseudo call

**Comment by ration665** [comment]
Hi Chidalu567,

Join me in sharing and discovering books on Goodreads!

https://www.goodreads.com/friend/i?e=reply%2BAT64IOV6SRPRONRYTFLQL7N6US2IVEVBNHHDGPQUF4%40reply.github.com&invite_token=MzNiNjkwM2ItOWI0MC00YjMwLWI5N2YtZmExNmUwMjIwYzJm&n=Chidalu567&utm_medium=email&utm_source=invite

- Chidalu
***@***.***)

Goodreads is a community for book lovers. It's a great way to get book recommendations from your friends and others. You can keep a list of books to read, join book clubs, and even take the never-ending book trivia quiz.


_____________________________


This email was sent by request to ***@***.***
To opt-out of future invites to Goodreads please follow this link: https://www.goodreads.com/user/block_email?email_to_block=aCt5c21YMHJlMlVpMXQxZzlTU2RXY3JJRlJNWHFFdjBIUTI2S2VhOExLQnl5NlR6ZHBRMVZ1eDdMRWUwUU9TTjlhRWJIWGN1eFBXSTJDc3BxZGQyOHlWRTkwL0tpVDU5cGlhcE1HSThYakE9LS1mdmY4UnNIQW5PRkxsam82SlBZRnRRPT0%3D--7d301325499dc00f18e44d5f368854a676e191b0&utm_medium=email&utm_source=invite

Questions? Visit Goodreads Help: https://www.goodreads.com/help?utm_medium=email&utm_source=invite

(c) 2021 Goodreads, Inc.
188 Spear Street, Suite 250, San Francisco, CA 94105

Privacy policy:
https://www.goodreads.com/about/privacy?utm_content=_privacy&utm_medium=email&utm_source=invite
